# Generated by Django 5.0.1 on 2024-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone", name="image", field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name="phone",
            name="lte_exists",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="phone",
            name="name",
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phone", name="price", field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="phone",
            name="release_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="phone", name="slug", field=models.SlugField(default=None),
        ),
        migrations.AlterField(
            model_name="phone",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
